# Generated by Django 4.0.8 on 2022-10-16 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_user_score'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to='tgbot.user'),
        ),
    ]
