# Generated by Django 4.0.8 on 2022-10-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_userexam_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexamanswer',
            name='option_ids',
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='option_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_anwer', to='exam.question'),
        ),
    ]
