# Generated by Django 4.0.6 on 2022-07-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_delete_subject'),
        ('exam', '0002_auto_20220712_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexam',
            name='questions',
            field=models.ManyToManyField(to='question.question'),
        ),
    ]
