# Generated by Django 4.0.8 on 2022-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_merge_20220712_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Imtihon', 'verbose_name_plural': 'Imtihonlar'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_datetime',
        ),
        migrations.AlterField(
            model_name='exam',
            name='content',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions_count',
            field=models.IntegerField(default=10, verbose_name='Savollar soni'),
        ),
    ]
