# Generated by Django 4.0.8 on 2022-10-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_exam_options_remove_exam_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='stage',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='exam',
            name='tour',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
