# Generated by Django 4.0.8 on 2022-10-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
        ('exam', '0008_question_questionoption_alter_exam_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='true_answered_users',
        ),
        migrations.AddField(
            model_name='question',
            name='true_answered_users',
            field=models.ManyToManyField(to='tgbot.user'),
        ),
    ]
