# Generated by Django 4.0.8 on 2022-10-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_remove_question_true_answered_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexamanswer',
            old_name='user_answer',
            new_name='user_exam',
        ),
    ]
