# Generated by Django 4.0.8 on 2022-10-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_rename_user_answer_userexamanswer_user_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamanswer',
            name='question_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.questionoption'),
        ),
    ]
