# Generated by Django 4.0.8 on 2022-10-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_userexamanswer_question_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexamanswer',
            name='question_option',
        ),
    ]
