# Generated by Django 4.0.8 on 2022-10-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
