# Generated by Django 4.0.8 on 2022-10-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='IsmiGul', max_length=128, null=True),
        ),
    ]
