# Generated by Django 4.0.8 on 2022-10-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
        ('question', '0003_delete_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='title',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='questionoption',
            old_name='questions',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='stage',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='tour',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='true_answered_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tgbot.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='true_definition',
            field=models.TextField(default=1, max_length=65536),
            preserve_default=False,
        ),
    ]
