# Generated by Django 4.0.8 on 2022-10-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_question_questionoption_alter_exam_questions_and_more'),
        ('question', '0005_questionfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
