# Generated by Django 4.0.8 on 2022-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='is_random_opponent',
            field=models.BooleanField(default=False),
        ),
    ]
