# Generated by Django 4.0.7 on 2022-09-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
        ('group_challenge', '0002_privatechallenge_rate_usertask_remove_progress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tgbot.user'),
            preserve_default=False,
        ),
    ]
