# Generated by Django 4.0.7 on 2022-09-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenge', '0003_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechallenge',
            name='users',
        ),
    ]
