# Generated by Django 4.0.8 on 2022-10-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenge', '0004_userchallenge_created_challenge_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='opponent_chat_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='opponent_message_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='user_chat_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='user_message_id',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
