# Generated by Django 4.0.8 on 2022-10-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenge', '0005_rename_starts_count_rate_old_stars_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('Ochiq', 'public'), ('Yopiq', 'private')], default='Ochiq', max_length=15),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('not_finished', 'not_finished'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='not_finished', max_length=15),
        ),
    ]
