# Generated by Django 4.0.8 on 2022-10-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_rename_user_answer_userexamanswer_user_exam'),
        ('group_challenge', '0006_alter_userchallenge_status_alter_usertask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_challenge',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='content',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='status',
        ),
        migrations.AddField(
            model_name='challenge',
            name='questions',
            field=models.ManyToManyField(to='exam.question'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='stage',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
