# Generated by Django 4.0.8 on 2022-10-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_rename_user_answer_userexamanswer_user_exam'),
        ('group_challenge', '0009_userchallenge_is_opponent_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='questions',
            field=models.ManyToManyField(to='exam.question'),
        ),
    ]
