# Generated by Django 4.0.8 on 2022-10-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_user_name'),
        ('group_challenge', '0010_userchallenge_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='tgbot.user'),
        ),
    ]
