# Generated by Django 4.0.8 on 2022-10-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenge', '0011_userchallenge_opponent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchallenge',
            old_name='started_at',
            new_name='opponent_started_at',
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='user_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
